### ISSUE TITLE
Problems with Android OS

### ISSUE THREAD

**Issue by hudiohizari** [jobtoday/react-native-image-viewing#30]
First problem is when you add ImageView component, it will prevent back button as shown on this video below
https://share.icloud.com/photos/0R3_N2HJN2wXlqc9v2itD2rQg

Second probelm is presentationStyle="overFullScreen" only fill parent as shown on this video below
https://share.icloud.com/photos/0Eim16y5lpvDFJXDaeQHyVxpA

**Comment by antonKalinin** [comment]
Hey @hudiohizari back button issue is fixed in v0.1.8

**Comment by hudiohizari** [comment]
@antonKalinin thanks for the update
after updating i tried to applied this to android device and its working for first time if you don't show the modal first, after show then hide the modal it throw this error :

**Comment by hudiohizari** [comment]
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, a useEffect cleanup function, 
    in ImageViewing (at ImageViewing.js:74)
    in EnhancedImageViewing (at DetailRoomImages.js:42)
    in RCTView (at DetailRoomImages.js:105)
    in RoomImages (at RoomDetailScreen.js:240)
    in RCTView (at Card.js:10)
    in RCTView (at Card.js:6)
    in Card (at RoomDetailScreen.js:238)
    in RCTView (at ScrollView.js:1038)
    in RCTScrollView (at ScrollView.js:1178)
    in ScrollView (at RoomDetailScreen.js:237)
    in RCTView (at KeyboardAvoidingView.js:174)
    in KeyboardAvoidingView (at RoomDetailScreen.js:227)
    in RoomDetailScreen (at SceneView.tsx:93)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:84)
    in EnsureSingleNavigator (at SceneView.tsx:83)
    in SceneView (at useDescriptors.tsx:111)
    in RCTView (at CardContainer.tsx:187)
    in RCTView (at CardContainer.tsx:186)
    in RCTView (at Card.tsx:508)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:491)
    in PanGestureHandler (at Card.tsx:484)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:480)
    in RCTView (at Card.tsx:473)
    in Card (at CardContainer.tsx:154)
    in CardContainer (at CardStack.tsx:580)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at CardStack.tsx:128)
    in MaybeScreen (at CardStack.tsx:573)
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:645:36 in warningWithoutStack
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:20432:6 in warnAboutUpdateOnUnmountedFiberInDEV
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18518:41 in scheduleUpdateOnFiber
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:11484:17 in dispatchAction
* [native code]:null in dispatchAction
- node_modules/react-native-image-viewing/dist/hooks/useRequestClose.js:12:8 in useRequestClose
- node_modules/react-native-image-viewing/dist/components/Modal/Modal.android.js:16:23 in BackHandler.addEventListener$argument_1
- node_modules/react-native/Libraries/Utilities/BackHandler.android.js:24:8 in RCTDeviceEventEmitter.addListener$argument_1
- node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:190:12 in emit
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by hudiohizari** [comment]
@antonKalinin thanks for the update
after updating i tried to applied this to android device and its working for first time if you don't show the modal first, after show then hide the modal it throw this error :

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, a useEffect cleanup function, 
    in ImageViewing (at ImageViewing.js:74)
    in EnhancedImageViewing (at DetailRoomImages.js:42)
    in RCTView (at DetailRoomImages.js:105)
    in RoomImages (at RoomDetailScreen.js:240)
    in RCTView (at Card.js:10)
    in RCTView (at Card.js:6)
    in Card (at RoomDetailScreen.js:238)
    in RCTView (at ScrollView.js:1038)
    in RCTScrollView (at ScrollView.js:1178)
    in ScrollView (at RoomDetailScreen.js:237)
    in RCTView (at KeyboardAvoidingView.js:174)
    in KeyboardAvoidingView (at RoomDetailScreen.js:227)
    in RoomDetailScreen (at SceneView.tsx:93)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:84)
    in EnsureSingleNavigator (at SceneView.tsx:83)
    in SceneView (at useDescriptors.tsx:111)
    in RCTView (at CardContainer.tsx:187)
    in RCTView (at CardContainer.tsx:186)
    in RCTView (at Card.tsx:508)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:491)
    in PanGestureHandler (at Card.tsx:484)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:480)
    in RCTView (at Card.tsx:473)
    in Card (at CardContainer.tsx:154)
    in CardContainer (at CardStack.tsx:580)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at CardStack.tsx:128)
    in MaybeScreen (at CardStack.tsx:573)
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:645:36 in warningWithoutStack
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:20432:6 in warnAboutUpdateOnUnmountedFiberInDEV
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18518:41 in scheduleUpdateOnFiber
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:11484:17 in dispatchAction
* [native code]:null in dispatchAction
- node_modules/react-native-image-viewing/dist/hooks/useRequestClose.js:12:8 in useRequestClose
- node_modules/react-native-image-viewing/dist/components/Modal/Modal.android.js:16:23 in BackHandler.addEventListener$argument_1
- node_modules/react-native/Libraries/Utilities/BackHandler.android.js:24:8 in RCTDeviceEventEmitter.addListener$argument_1
- node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:190:12 in emit
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue
```

and for the second issue it's still occurring

**Comment by rleira** [comment]
Just installed this and I'm having the second issue too:

> Second probelm is presentationStyle="overFullScreen" only fill parent as shown on this video below
https://share.icloud.com/photos/0Eim16y5lpvDFJXDaeQHyVxpA

On iOS works great.

Currently using the following versions of react and react-native:
    "react": "16.8.1",
    "react-native": "0.61.2",

Did anyone found a solution for this bug?

**Comment by hjhimanshu01** [comment]
@hudiohizari , same issue here, backButton isn't working

**Comment by me1k** [comment]
for me neither

**Comment by me1k** [comment]
will this be fixed in the near future?

**Comment by GoktuqCan** [comment]
Having same issue with `v0.1.8`. Any updates?

**Comment by hjhimanshu01** [comment]
@GoktuqCan  `react-native-image-view` seems to be working although it's deprecated, it could help

**Comment by anandhakumarpalanisamy** [comment]
> @GoktuqCan `react-native-image-view` seems to be working although it's deprecated, it could help

But it has the warning for react-native v0.62 +  

"WARN Animated: "useNativeDriver" was not specified. This is a required option and must be explicitly set to "true" or "false""

**Comment by me1k** [comment]
I really would appreciate, if this bug with the back button would be fixed. I really like this package :/
